[Unit]
Description=Unique & Antique Django Backend
After=network.target postgresql.service

[Service]
Type=exec
User=cloudpanel
Group=cloudpanel
WorkingDirectory=/home/cloudpanel/htdocs/backend.unique-antique.com
Environment=DJANGO_SETTINGS_MODULE=config.settings.production
ExecStart=/home/cloudpanel/htdocs/backend.unique-antique.com/venv/bin/gunicorn --config gunicorn_config.py config.wsgi:application
ExecReload=/bin/kill -s HUP $MAINPID
Restart=always
RestartSec=3
KillMode=mixed
TimeoutStopSec=5
PrivateTmp=true

[Install]
WantedBy=multi-user.target
