# Generated by Django 5.0.7 on 2025-10-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('order', 'Order Related'), ('return', 'Return/Exchange'), ('product', 'Product Question'), ('technical', 'Technical Support'), ('complaint', 'Complaint'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=50, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
