# Generated by Django 5.0.7 on 2025-10-02 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='order number')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='order ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='order status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('payment_method', models.CharField(choices=[('stripe', 'Credit/Debit Card'), ('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=20, verbose_name='payment method')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax amount')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='shipping cost')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('shipping_address', models.JSONField(help_text='Shipping address details as JSON', verbose_name='shipping address')),
                ('billing_address', models.JSONField(help_text='Billing address details as JSON', verbose_name='billing address')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='shipping method')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='tracking number')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='carrier')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes from customer', verbose_name='customer notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('product_sku', models.CharField(max_length=100, verbose_name='product SKU')),
                ('variant_name', models.CharField(blank=True, max_length=100, verbose_name='variant name')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total price')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Item options or customizations', verbose_name='item options')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant', verbose_name='product variant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orders_orderitem',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='return number')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Received'), ('processed', 'Processed'), ('refunded', 'Refunded')], default='requested', max_length=20, verbose_name='return status')),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('damaged_shipping', 'Damaged in Shipping'), ('changed_mind', 'Changed Mind'), ('size_fit', 'Size/Fit Issues'), ('other', 'Other')], max_length=20, verbose_name='return reason')),
                ('customer_notes', models.TextField(help_text='Customer explanation for return', verbose_name='customer notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes', verbose_name='admin notes')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='refund amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Order Return',
                'verbose_name_plural': 'Order Returns',
                'db_table': 'orders_orderreturn',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='return quantity')),
                ('condition', models.CharField(blank=True, help_text='Condition of returned item', max_length=100, verbose_name='item condition')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem', verbose_name='order item')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderreturn', verbose_name='return request')),
            ],
            options={
                'verbose_name': 'Order Return Item',
                'verbose_name_plural': 'Order Return Items',
                'db_table': 'orders_orderreturnitem',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='tracking number')),
                ('carrier', models.CharField(max_length=100, verbose_name='carrier')),
                ('service_type', models.CharField(blank=True, help_text='Express, Standard, etc.', max_length=100, verbose_name='service type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned')], default='pending', max_length=20, verbose_name='shipment status')),
                ('origin_address', models.JSONField(help_text='Warehouse/origin address', verbose_name='origin address')),
                ('destination_address', models.JSONField(help_text='Customer delivery address', verbose_name='destination address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='weight (kg)')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='Package dimensions (length, width, height)', verbose_name='dimensions')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Order Shipment',
                'verbose_name_plural': 'Order Shipments',
                'db_table': 'orders_ordershipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about status change', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'db_table': 'orders_orderstatushistory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='orders_orde_status_c50fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_5adf88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['return_number'], name='orders_orde_return__7b0329_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderreturnitem',
            unique_together={('return_request', 'order_item')},
        ),
        migrations.AddIndex(
            model_name='ordershipment',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_5a805b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordershipment',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_d8aee9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_1de1d7_idx'),
        ),
    ]
