# Generated by Django 5.0.7 on 2025-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PKR', max_length=3, verbose_name='currency'),
        ),
    ]
