# Generated by Django 5.0.7 on 2025-10-02 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='review ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(help_text='Short title for the review', max_length=200, verbose_name='review title')),
                ('content', models.TextField(help_text='Detailed review content', verbose_name='review content')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('hidden', 'Hidden')], default='pending', max_length=20, verbose_name='status')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Review from verified purchaser', verbose_name='verified purchase')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review helpful', verbose_name='helpful count')),
                ('not_helpful_count', models.PositiveIntegerField(default=0, help_text='Number of users who found this review not helpful', verbose_name='not helpful count')),
                ('moderation_notes', models.TextField(blank=True, help_text='Internal notes for moderation', verbose_name='moderation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='moderated by')),
                ('order', models.ForeignKey(blank=True, help_text='Order this review is based on (for verified purchases)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True if user found review helpful, False otherwise', verbose_name='is helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='reviews.review', verbose_name='review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Review Helpfulness Vote',
                'verbose_name_plural': 'Review Helpfulness Votes',
                'db_table': 'reviews_reviewhelpfulness',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Review image', upload_to='reviews/', verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=200, verbose_name='caption')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order of images', verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'db_table': 'reviews_reviewimage',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='report ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('fake', 'Fake Review'), ('offensive', 'Offensive Language'), ('irrelevant', 'Irrelevant to Product'), ('personal_info', 'Contains Personal Information'), ('other', 'Other')], max_length=20, verbose_name='reason')),
                ('description', models.TextField(blank=True, help_text='Additional details about the report', verbose_name='description')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the report was resolved', verbose_name='resolution notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_review_reports', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'Review Report',
                'verbose_name_plural': 'Review Reports',
                'db_table': 'reviews_reviewreport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Response to the review', verbose_name='response content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('responder', models.ForeignKey(help_text='Admin/staff member who responded', on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL, verbose_name='responder')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review', verbose_name='review')),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Responses',
                'db_table': 'reviews_reviewresponse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from all approved reviews', max_digits=3, verbose_name='average rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, help_text='Total number of approved reviews', verbose_name='total reviews')),
                ('rating_1_count', models.PositiveIntegerField(default=0, verbose_name='1 star count')),
                ('rating_2_count', models.PositiveIntegerField(default=0, verbose_name='2 star count')),
                ('rating_3_count', models.PositiveIntegerField(default=0, verbose_name='3 star count')),
                ('rating_4_count', models.PositiveIntegerField(default=0, verbose_name='4 star count')),
                ('rating_5_count', models.PositiveIntegerField(default=0, verbose_name='5 star count')),
                ('verified_reviews_count', models.PositiveIntegerField(default=0, help_text='Number of reviews from verified purchases', verbose_name='verified reviews count')),
                ('verified_average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from verified purchases only', max_digits=3, verbose_name='verified average rating')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stats', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Rating Statistics',
                'verbose_name_plural': 'Product Rating Statistics',
                'db_table': 'reviews_productrating',
                'indexes': [models.Index(fields=['average_rating'], name='reviews_pro_average_2362df_idx'), models.Index(fields=['total_reviews'], name='reviews_pro_total_r_d05ddb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status'], name='reviews_rev_product_0aaa55_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'status'], name='reviews_rev_user_id_194b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'status'], name='reviews_rev_rating_d477ad_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase', 'status'], name='reviews_rev_is_veri_9b23f6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('product', 'user', 'order')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpfulness',
            index=models.Index(fields=['review', 'is_helpful'], name='reviews_rev_review__6a0b5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='reviewimage',
            index=models.Index(fields=['review', 'position'], name='reviews_rev_review__52fbc8_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review', 'status'], name='reviews_rev_review__d11166_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='reviews_rev_status_a3683e_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['assigned_to', 'status'], name='reviews_rev_assigne_c9cc63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewreport',
            unique_together={('review', 'reporter')},
        ),
        migrations.AddIndex(
            model_name='reviewresponse',
            index=models.Index(fields=['review', 'status'], name='reviews_rev_review__27d7b1_idx'),
        ),
    ]
