# Generated by Django 5.0.7 on 2025-10-02 07:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='payment ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet')], max_length=20, verbose_name='payment provider')),
                ('provider_payment_id', models.CharField(blank=True, help_text='Payment ID from payment provider', max_length=255, verbose_name='provider payment ID')),
                ('provider_payment_intent_id', models.CharField(blank=True, help_text='Payment intent ID from provider (Stripe)', max_length=255, verbose_name='provider payment intent ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='payment status')),
                ('payment_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund')], default='payment', max_length=20, verbose_name='payment type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='processing fee')),
                ('payment_method_details', models.JSONField(blank=True, default=dict, help_text='Details about payment method (card last 4, etc.)', verbose_name='payment method details')),
                ('billing_address', models.JSONField(blank=True, default=dict, help_text='Billing address for this payment', verbose_name='billing address')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata', verbose_name='metadata')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure', verbose_name='failure reason')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes', verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='refunded amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_account', 'Bank Account'), ('digital_wallet', 'Digital Wallet')], max_length=20, verbose_name='payment method type')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet')], max_length=20, verbose_name='provider')),
                ('provider_payment_method_id', models.CharField(help_text='Payment method ID from provider', max_length=255, verbose_name='provider payment method ID')),
                ('display_name', models.CharField(help_text='User-friendly name for payment method', max_length=100, verbose_name='display name')),
                ('last_four', models.CharField(blank=True, help_text='Last 4 digits of card/account', max_length=4, verbose_name='last four digits')),
                ('brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=50, verbose_name='brand')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('expires_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='expiration month')),
                ('expires_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='expiration year')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payments_paymentmethod',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='refund ID')),
                ('provider_refund_id', models.CharField(blank=True, help_text='Refund ID from payment provider', max_length=255, verbose_name='provider refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='refund amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='refund status')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='refund reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'db_table': 'payments_paymentrefund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='transaction ID')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='provider transaction ID')),
                ('action', models.CharField(choices=[('authorize', 'Authorize'), ('capture', 'Capture'), ('charge', 'Charge'), ('refund', 'Refund'), ('void', 'Void'), ('cancel', 'Cancel')], max_length=20, verbose_name='action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response data from payment provider', verbose_name='response data')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'db_table': 'payments_paymenttransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='webhook ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Digital Wallet')], max_length=20, verbose_name='provider')),
                ('provider_webhook_id', models.CharField(blank=True, max_length=255, verbose_name='provider webhook ID')),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100, verbose_name='event type')),
                ('event_data', models.JSONField(help_text='Full webhook event data', verbose_name='event data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20, verbose_name='processing status')),
                ('processing_notes', models.TextField(blank=True, help_text='Notes about webhook processing', verbose_name='processing notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment', verbose_name='related payment')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'db_table': 'payments_paymentwebhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status'], name='payments_pa_provide_cc7861_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_payment_id'], name='payments_pa_provide_adf74c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payments_pa_user_id_bd2d73_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider_payment_method_id'], name='payments_pa_provide_5b3ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment', 'status'], name='payments_pa_payment_2735e7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['provider_refund_id'], name='payments_pa_provide_d061a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'action'], name='payments_pa_payment_d012bf_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider', 'event_type'], name='payments_pa_provide_cbd3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_f210fa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['provider_webhook_id'], name='payments_pa_provide_ad9237_idx'),
        ),
    ]
