# Generated by Django 5.0.7 on 2025-10-10 10:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(blank=True, help_text="Subscriber's name (optional)", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user subscribed')),
                ('unsubscribed_at', models.DateTimeField(blank=True, help_text='When the user unsubscribed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when subscribed', null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Newsletter title', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('content', models.TextField(help_text='Newsletter content (HTML supported)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', help_text='Newsletter status', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the newsletter was created')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to send the newsletter', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the newsletter was sent', null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0, help_text='Number of recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, help_text='Number of emails sent successfully')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='Number of emails that failed to send')),
                ('created_by', models.ForeignKey(help_text='User who created the newsletter', on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True, help_text='Whether the email was sent successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='newsletter.newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='newsletter.newslettersubscriber')),
            ],
            options={
                'verbose_name': 'Newsletter Send Log',
                'verbose_name_plural': 'Newsletter Send Logs',
                'db_table': 'newsletter_send_logs',
                'ordering': ['-sent_at'],
                'unique_together': {('newsletter', 'subscriber')},
            },
        ),
    ]
