# Generated by Django 5.0.7 on 2025-10-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticity_verified',
            field=models.BooleanField(default=True, help_text='Whether the item has been verified as authentic', verbose_name='authenticity verified'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.JSONField(blank=True, default=list, help_text='List of care instructions for the product', verbose_name='care instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, help_text='Product condition (e.g., Authentic Antique, Vintage, etc.)', max_length=100, verbose_name='condition'),
        ),
        migrations.AddField(
            model_name='product',
            name='era',
            field=models.CharField(blank=True, help_text='Historical era or period', max_length=100, verbose_name='era'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Primary materials used', max_length=200, verbose_name='material'),
        ),
    ]
