# Generated by Django 5.0.7 on 2025-10-13 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_sample_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allow_backorders',
            field=models.BooleanField(default=False, help_text='Check this to let customers order even when you have 0 stock (useful for made-to-order items).', verbose_name='Allow Orders When Out of Stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Add product features like "Material: Wood, Color: Brown, Weight: 5kg" - one per line. System will automatically format this.', verbose_name='Product Features & Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Select the brand or manufacturer if known. Leave blank if unknown or generic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Brand/Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_instructions',
            field=models.JSONField(blank=True, default=list, help_text='Add care instructions like "Dust with soft cloth, Avoid direct sunlight, Keep away from moisture" - one per line. System will automatically format this.', verbose_name='Care Instructions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Choose the most appropriate category. This helps customers find your product when browsing.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If this item is on sale, enter the original higher price here to show customers the discount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Original Price (PKR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What you paid for this item (for your profit tracking). This is private and not shown to customers.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Your Cost Price (PKR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Write a detailed description highlighting key features, history, and condition. This helps customers make informed decisions.', verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False, help_text="Check this for digital downloads, services, or virtual items that don't need shipping.", verbose_name='Digital Product (No Physical Item)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products are highlighted on the homepage and get more visibility to customers.', verbose_name='Feature This Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Get notified when stock drops to this number. Recommended: 5-10 items.', verbose_name='Low Stock Alert Level'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price customers will pay. Enter amount in Pakistani Rupees (e.g., 25000 for PKR 25,000)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Selling Price (PKR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='requires_shipping',
            field=models.BooleanField(default=True, help_text="Uncheck this for pickup-only items or digital products that don't need shipping.", verbose_name='Needs to be Shipped'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief summary (1-2 sentences) that appears in product listings. Keep it engaging and informative.', max_length=500, verbose_name='Short Summary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='A unique code for this product (e.g., "VIC-TABLE-001"). Use letters, numbers, and dashes only.', max_length=100, unique=True, verbose_name='Product Code (SKU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='This creates the web address for your product. Leave blank to auto-generate from title.', max_length=220, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='draft', help_text='Draft = Not visible to customers | Active = Visible on website | Inactive = Hidden temporarily | Discontinued = No longer available', max_length=20, verbose_name='Product Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of items you have in stock. Set to 0 if out of stock.', verbose_name='How Many Do You Have?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Enter a clear, descriptive title that customers will search for. Example: "Victorian Oak Dining Table"', max_length=200, verbose_name='Product Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_inventory',
            field=models.BooleanField(default=True, help_text='Check this to automatically track when items are sold and update stock levels.', verbose_name='Track Stock Levels'),
        ),
    ]
