# Generated by Django 5.0.7 on 2025-10-06 08:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zone name (e.g., Karachi, Lahore)', max_length=100)),
                ('code', models.CharField(help_text='Zone code (e.g., KHI, LHE)', max_length=20, unique=True)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Standard shipping cost for this zone (PKR)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('express_cost', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Express shipping cost for this zone (PKR)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('standard_delivery_days', models.PositiveIntegerField(default=3, help_text='Standard delivery time in days')),
                ('express_delivery_days', models.PositiveIntegerField(default=1, help_text='Express delivery time in days')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('8.25'), help_text='Tax rate as percentage (e.g., 8.25 for 8.25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('tax_enabled', models.BooleanField(default=True, help_text='Enable/disable tax calculation')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('25000.00'), help_text='Minimum order amount for free shipping (PKR)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('standard_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Standard shipping cost (PKR)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('express_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Express shipping cost (PKR)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('shipping_enabled', models.BooleanField(default=True, help_text='Enable/disable shipping cost calculation')),
                ('currency_code', models.CharField(default='PKR', help_text='Currency code (e.g., PKR, USD)', max_length=3)),
                ('currency_symbol', models.CharField(default='PKR', help_text='Currency symbol to display', max_length=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum order amount (PKR)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tax rate name (e.g., GST, VAT)', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('region', models.CharField(blank=True, help_text='Region (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product category (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['name'],
            },
        ),
    ]
